// Generated by lsc from splitBill.fixed.ts

function JSFloorDiv(a: int, b: int): int
  requires b != 0
{
  if b > 0 then
    if a >= 0 then a / b
    else -((-a - 1) / b) - 1
  else
    if a <= 0 then (-a) / (-b)
    else -((a - 1) / (-b)) - 1
}

datatype Split = Split(each: int, last: int)

function splitBill(total: int, people: int): Split
  requires (total >= 0)
  requires (people >= 1)
{
  var each := JSFloorDiv(total, people);
  var last := (total - (each * (people - 1)));
  Split(each, last)
}

lemma splitBill_ensures(total: int, people: int)
  requires (total >= 0)
  requires (people >= 1)
  ensures (((splitBill(total, people).each * (people - 1)) + splitBill(total, people).last) == total)
  ensures (splitBill(total, people).last >= 0)
  ensures (splitBill(total, people).each >= 0)
{
}
