// Generated by lsc from splitBill.ts

function CeilReal(x: real): int
{
  if x == (x.Floor as real) then x.Floor
  else x.Floor + 1
}

datatype Split = Split(each: int, last: int)

function splitBill(total: int, people: int): Split
  requires (total >= 0)
  requires (people >= 1)
{
  var each := CeilReal(((total as real) / (people as real)));
  var last := (total - (each * (people - 1)));
  Split(each, last)
}

lemma splitBill_ensures(total: int, people: int)
  requires (total >= 0)
  requires (people >= 1)
  ensures (((splitBill(total, people).each * (people - 1)) + splitBill(total, people).last) == total)
  ensures (splitBill(total, people).last >= 0)
  ensures (splitBill(total, people).each >= 0)
{
}
